
spring.application.name=resumebuilder

# Mongodb Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/resumebuilder

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587

# Your Brevo SMTP login
spring.mail.username=my_account

# Your Brevo SMTP key
spring.mail.password=password

# SMTP Authentication
spring.mail.properties.mail.smtp.auth=true

# Enable TLS
spring.mail.properties.mail.smtp.starttls.enable=true

smtp.mail.properties.mail.smtp.from=bhadoriaakash3@gmail.com

app.base.url=http://localhost:8080

#cloudinary configuration
cloudinary.cloud-name=eessse6q
cloudinary.api-key=695687324443719
cloudinary.api-secret=38zyP-WhrxaqXE1OteXsRDS3Qiw

