
spring.application.name=resumebuilder

# Mongodb Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/resumebuilder

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587

# Your Brevo SMTP login
spring.mail.username=b083bd007@smtp-brevo.com

# Your Brevo SMTP key
spring.mail.password=xsmtpsib-9c18f53d421e3aa2f9569f6330e6ee2f291afc3d6eaca4a9f15b38abd9d3606d-nUSGJeFlxkRVL3d5

# SMTP Authentication
spring.mail.properties.mail.smtp.auth=true

# Enable TLS
spring.mail.properties.mail.smtp.starttls.enable=true

smtp.mail.properties.mail.smtp.from=bhadoriaakash3@gmail.com


#Base url :
app.base.url=http://localhost:8080

#Cloudinary configuration
cloudinary.cloud-name=eessse6q
cloudinary.api-key=695687324443719
cloudinary.api-secret=secret

#JWT configuration
jwt.secret=ThisIsMyVeryStrongJwtSecretKeyForResumeBuilder123456
jwt.expiration=604800000

#razorPay configuration
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}


